//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERV_Catalogo_otros_servicios
    {
        public int CodSer { get; set; }
        public string DesSer { get; set; }
        public string Notas { get; set; }
    }
}
