//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_Detalle_Reserva
    {
        public int CodReserva { get; set; }
        public int Numreg { get; set; }
        public Nullable<System.DateTime> FecHoraRes { get; set; }
        public string CodSer { get; set; }
        public string CodSala { get; set; }
        public Nullable<int> CodTerap { get; set; }
        public string Notas { get; set; }
        public string NomHues { get; set; }
    
        public virtual SPA_Encabezado_Reserva SPA_Encabezado_Reserva { get; set; }
        public virtual SPA_Salas SPA_Salas { get; set; }
        public virtual SPA_Servicios SPA_Servicios { get; set; }
        public virtual SPA_Terapeutas SPA_Terapeutas { get; set; }
    }
}
