//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SPA_Detalle_Reserva
    {
        [Display(Name = "Código")]
        public int CodReserva { get; set; }
        [Display(Name = "Número registro")]
        [Required]
        public int Numreg { get; set; }
        [Display(Name = "Fecha/Hora registro")]
        [Required]
        public Nullable<System.DateTime> FecHoraRes { get; set; }
        [Display(Name = "Servicio")]
        [Required]
        public string CodSer { get; set; }
        [Display(Name = "Sala")]
        [Required]
        public string CodSala { get; set; }
        [Display(Name = "Terapeuta")]
        [Required]
        public Nullable<int> CodTerap { get; set; }
        [Display(Name = "Notas")]
        public string Notas { get; set; }
        [Display(Name = "Nombre Huesped")]
        [Required]
        public string NomHues { get; set; }

        public virtual SPA_Encabezado_Reserva SPA_Encabezado_Reserva { get; set; }
        public virtual SPA_Salas SPA_Salas { get; set; }
        public virtual SPA_Servicios SPA_Servicios { get; set; }
        public virtual SPA_Terapeutas SPA_Terapeutas { get; set; }
    }
}
