//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_Terapeutas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPA_Terapeutas()
        {
            this.SPA_Detalle_Reserva = new HashSet<SPA_Detalle_Reserva>();
        }
    
        public int CodTerap { get; set; }
        public string NomTerap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_Detalle_Reserva> SPA_Detalle_Reserva { get; set; }
    }
}
