//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_Encabezado_Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPA_Encabezado_Reserva()
        {
            this.SPA_Detalle_Reserva = new HashSet<SPA_Detalle_Reserva>();
        }
    
        public int CodReserva { get; set; }
        public string ReservaOpera { get; set; }
        public string NomHuesped { get; set; }
        public string NumRoom { get; set; }
        public Nullable<System.DateTime> Checkin { get; set; }
        public Nullable<System.DateTime> Checkout { get; set; }
        public Nullable<System.DateTime> FecReg { get; set; }
        public string UsrReg { get; set; }
        public string Alergias { get; set; }
        public string Observaciones { get; set; }
        public string NotasCliente { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_Detalle_Reserva> SPA_Detalle_Reserva { get; set; }
    }
}
