//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_Encabezado_Reserva
    {
        public int CodReserva { get; set; }
        public string ReservaOpera { get; set; }
        public string NomHuesped { get; set; }
        public string NumRoom { get; set; }
        public Nullable<System.DateTime> Checkin { get; set; }
        public Nullable<System.DateTime> Checkout { get; set; }
        public Nullable<System.DateTime> FecReg { get; set; }
        public string UsrReg { get; set; }
        public string Alergias { get; set; }
        public string Observaciones { get; set; }
        public string NotasCliente { get; set; }
        public string Email { get; set; }
        public Nullable<int> CodCom { get; set; }
        public Nullable<int> CodTour { get; set; }
        public Nullable<int> PaxAdul { get; set; }
        public Nullable<int> PaxAdulM { get; set; }
        public Nullable<int> PaxNino { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<System.TimeSpan> ReturnTime { get; set; }
    
        public virtual TOUR_Catalogo_Tour TOUR_Catalogo_Tour { get; set; }
        public virtual TOUR_Operadores TOUR_Operadores { get; set; }
    }
}
