//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR_Catalogo_Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR_Catalogo_Tour()
        {
            this.TOUR_Encabezado_Reserva = new HashSet<TOUR_Encabezado_Reserva>();
        }
    
        public int CodTour { get; set; }
        public string NomTour { get; set; }
        public string DesTour { get; set; }
        public Nullable<System.TimeSpan> DurTour { get; set; }
        public Nullable<decimal> PreTourAdulto { get; set; }
        public Nullable<decimal> PreTourAdultoM { get; set; }
        public Nullable<decimal> PreTourNino { get; set; }
        public string NotasTour { get; set; }
        public Nullable<int> ComTour { get; set; }
    
        public virtual TOUR_Operadores TOUR_Operadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_Encabezado_Reserva> TOUR_Encabezado_Reserva { get; set; }
    }
}
