//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TOUR_Operadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR_Operadores()
        {
            this.TOUR_Catalogo_Tour = new HashSet<TOUR_Catalogo_Tour>();
            this.TOUR_Encabezado_Reserva = new HashSet<TOUR_Encabezado_Reserva>();
        }

        [Display(Name = "Código operador")]
        [Required]
        public int CodCom { get; set; }
        [Display(Name = "Nombre operador")]
        [Required]
        public string NomCom { get; set; }
        [Display(Name = "Télefono")]
        [Required]
        [Phone]
        public string TelCom { get; set; }
        [Display(Name = "Email")]
        [Required]
        [EmailAddress]
        public string EmaCom { get; set; }
        [Display(Name = "Contacto 1")]
        [Required]
        public string Contacto1 { get; set; }
        [Display(Name = "Télefono 1")]
        [Required]
        [Phone]
        public string Telcon1 { get; set; }
        [Display(Name = "Email")]
        [Required]
        [EmailAddress]
        public string EmaCon1 { get; set; }
        [Display(Name = "Contacto 2")]
        [Required]
        public string Contacto2 { get; set; }
        [Display(Name = "Télefono 2")]
        [Required]
        [Phone]
        public string Telcon2 { get; set; }
        [Display(Name = "Email")]
        [Required]
        [EmailAddress]
        public string Emacon2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_Catalogo_Tour> TOUR_Catalogo_Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOUR_Encabezado_Reserva> TOUR_Encabezado_Reserva { get; set; }
    }
}
