//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TRAN_Pick_Drop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAN_Pick_Drop()
        {
            this.TRAN_Encabezado_Reserva = new HashSet<TRAN_Encabezado_Reserva>();
            this.TRAN_Encabezado_Reserva1 = new HashSet<TRAN_Encabezado_Reserva>();
        }

        [Display(Name = "Código")]
        [Required]
        public int CodPick { get; set; }
        [Display(Name = "Descripción")]
        [Required]
        public string DesPick { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAN_Encabezado_Reserva> TRAN_Encabezado_Reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAN_Encabezado_Reserva> TRAN_Encabezado_Reserva1 { get; set; }
    }
}
