//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TRAN_Encabezado_Reserva
    {
        [Display(Name = "Código")]
        [Required]
        public int CodReserva { get; set; }
        [Display(Name = "Reserva Opera")]
        public string ReservaOpera { get; set; }
        [Display(Name = "Nombre huesped")]
        [Required]
        public string NomHuesped { get; set; }
        [Display(Name = "Número habitación")]
        public Nullable<int> NumRoom { get; set; }
        [Display(Name = "Check In")]
        public Nullable<System.DateTime> Checkin { get; set; }
        [Display(Name = "Check Out")]
        public Nullable<System.DateTime> Checkout { get; set; }
        [Display(Name = "Fecha registro")]
        [Required]
        public Nullable<System.DateTime> FecReg { get; set; }
        [Display(Name = "Usuario resgistro")]
        [Required]
        public string UsrReg { get; set; }
        [Display(Name = "Alergias")]
        public string Alergias { get; set; }
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; }
        [Display(Name = "Notas")]
        public string NotasCliente { get; set; }
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }
        [Display(Name = "Tipo transporte")]
        [Required]
        public Nullable<int> TipoTran { get; set; }
        [Display(Name = "Pick up")]
        [Required]
        public Nullable<int> Pickup { get; set; }
        [Display(Name = "Drop off")]
        [Required]
        public Nullable<int> Dropoff { get; set; }
        [Display(Name = "Pax")]
        [Required]
        public Nullable<int> Pax { get; set; }
        [Display(Name = "Precio")]
        [Required]
        public Nullable<decimal> Precio { get; set; }
        [Display(Name = "Fecha")]
        [Required]
        public Nullable<System.DateTime> Fecha { get; set; }
        [Display(Name = "Hora")]
        [Required]
        public Nullable<System.TimeSpan> Hora { get; set; }
        [Display(Name = "Aerolinea")]
        [Required]
        public string Aerolinea { get; set; }
        [Display(Name = "Número vuelo")]
        [Required]
        public string NoVuelo { get; set; }
    
        public virtual TRAN_Pick_Drop TRAN_Pick_Drop { get; set; }
        public virtual TRAN_Pick_Drop TRAN_Pick_Drop1 { get; set; }
        public virtual TRAN_Tipo_Transporte TRAN_Tipo_Transporte { get; set; }
    }
}
