//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAN_Encabezado_Reserva
    {
        public int CodReserva { get; set; }
        public string ReservaOpera { get; set; }
        public string NomHuesped { get; set; }
        public string NumRoom { get; set; }
        public Nullable<System.DateTime> Checkin { get; set; }
        public Nullable<System.DateTime> Checkout { get; set; }
        public Nullable<System.DateTime> FecReg { get; set; }
        public string UsrReg { get; set; }
        public string Alergias { get; set; }
        public string Observaciones { get; set; }
        public string NotasCliente { get; set; }
        public string Email { get; set; }
        public Nullable<int> TipoTran { get; set; }
        public Nullable<int> Pickup { get; set; }
        public Nullable<int> Dropoff { get; set; }
        public Nullable<int> Pax { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string Aerolinea { get; set; }
        public string NoVuelo { get; set; }
    
        public virtual TRAN_Pick_Drop TRAN_Pick_Drop { get; set; }
        public virtual TRAN_Pick_Drop TRAN_Pick_Drop1 { get; set; }
        public virtual TRAN_Tipo_Transporte TRAN_Tipo_Transporte { get; set; }
    }
}
