//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConciergeEntities : DbContext
    {
        public ConciergeEntities()
            : base("name=ConciergeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SPA_Salas> SPA_Salas { get; set; }
        public virtual DbSet<SPA_Servicios> SPA_Servicios { get; set; }
        public virtual DbSet<Tran_Pick_Drop> Tran_Pick_Drop { get; set; }
        public virtual DbSet<Tran_Tipo_Transporte> Tran_Tipo_Transporte { get; set; }
        public virtual DbSet<SPA_Detalle_Reserva> SPA_Detalle_Reserva { get; set; }
        public virtual DbSet<SPA_Encabezado_Reserva> SPA_Encabezado_Reserva { get; set; }
        public virtual DbSet<SPA_Terapeutas> SPA_Terapeutas { get; set; }
    }
}
