//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SPA_Servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPA_Servicios()
        {
            this.SPA_Detalle_Reserva = new HashSet<SPA_Detalle_Reserva>();
        }

        [Required(ErrorMessage = "Este campo no puede ser vacio.")]
        public string CodSer { get; set; }

        [Required(ErrorMessage = "Este campo no puede ser vacio.")]
        public string NomSer { get; set; }

        [Required(ErrorMessage = "Este campo no puede ser vacio.")]
        public string DesSer { get; set; }

        [Required(ErrorMessage = "Este campo no puede ser vacio.")]
        public Nullable<System.TimeSpan> DurSer { get; set; }

        public Nullable<decimal> PreSer { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_Detalle_Reserva> SPA_Detalle_Reserva { get; set; }
    }
}
