//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciergeV1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SPA_Salas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPA_Salas()
        {
            this.SPA_Detalle_Reserva = new HashSet<SPA_Detalle_Reserva>();
        }

        [Required(ErrorMessage = "Este campo no puede ser vacio.")]
        [StringLength(5, ErrorMessage = "El campo no puede ser mayor a 5 caracteres.")]
        public string CodSala { get; set; }

        [Required(ErrorMessage = "Este campo no puede ser vacio.")]
        public string DesSala { get; set; }

        [Required(ErrorMessage = "Este campo no puede ser vacio.")]
        public string CarSala { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPA_Detalle_Reserva> SPA_Detalle_Reserva { get; set; }
    }
}
